version: '3.2'

volumes:
  dbs: ~
  caches: ~

services:
  php:
    build: './Docker/php'
    networks:
      - backend
    volumes:
      - ./:/var/www/html/

  apache:
    build: './Docker/apache/'
    depends_on:
      - php
      - db
    networks:
      - frontend
      - backend
    ports:
      - "4000:80"
    volumes:
      - ./:/var/www/html/
  
  db:
    image: mariadb
    restart: always
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbs:/var/lib/mysql
    expose:
      - 3306

  adminer:
    image: adminer
    restart: always
    networks:
      - backend
    ports:
      - 5000:8080
  
  redis:
    image: redis:5.0.4-alpine
    restart: always
    networks:
      - backend
      - frontend
    expose:
      - 6379
    volumes:
      - caches:/data

networks:
  frontend:
  backend: